name: Build and Deploy Pipeline

on:
  push:
    branches:
      - main
      - devops/add-ci-pipeline

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Check Java version
        run: java -version

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: hw1-app
          path: 'target/*.jar'

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Download built Maven artifact
        uses: actions/download-artifact@v4
        with:
          name: hw1-app
      - name: Log in to GitHub Container Registry
        run: docker login ghcr.io -u simonkajanos93 -p ${{ github.token }}
      - name: Build Docker image
        run: docker build . -t ghcr.io/simonkajanos93/cubix-cloudnative-block1-homework/app:springboot
      - name: Push Docker image
        run: docker push ghcr.io/simonkajanos93/cubix-cloudnative-block1-homework/app:springboot
  verify:
    name: Verify Docker Image
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        run: docker login ghcr.io -u simonkajanos93 -p ${{ github.token }}
      - name: Run verify script
        run: |
          chmod +x ./verify-image.sh
          ./verify-image.sh